const express = require("express");
const path = require("path");
require("dotenv").config();

const app = express();
const PORT = process.env.PORT || 3000;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

app.use(express.json({ limit: "1mb" }));
app.use(express.static(path.join(__dirname, "public")));

function requireKey(req,res,next){if(!OPENAI_API_KEY)return res.status(500).json({error:"OPENAI_API_KEY が設定されていません。"});next();}
function outputText(data){if(typeof data.output_text==="string")return data.output_text;return(data.output||[]).flatMap(i=>i.content||[]).filter(i=>i.type==="output_text").map(i=>i.text||"").join("\n");}
function parseJson(text){return JSON.parse(String(text||"").replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/\s*```$/i,"").trim());}
async function generateJson(prompt){const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:prompt,reasoning:{effort:"none"}})});const data=await r.json();if(!r.ok)throw new Error(data.error?.message||"OpenAI API error");return parseJson(outputText(data));}

function answerIndex(q){const n=Number(q.answer_index);return Number.isInteger(n)&&n>=0&&n<=3?n:null;}
function validateQuestions(qs,expected){if(!Array.isArray(qs)||qs.length!==expected)throw new Error("問題の生成形式が不正でした。");for(const q of qs){if(!Array.isArray(q.options)||q.options.length!==4)throw new Error("選択肢の生成形式が不正でした。");const n=answerIndex(q);if(n===null)throw new Error("answer_index が不正です。");q.answer_index=n;}}
function hasJapanese(t){return/[\u3040-\u30ff\u3400-\u9fff]/u.test(String(t||""));}
function hasLatin(t){return/[A-Za-z]/.test(String(t||""));}
function normalizeWord(t){return String(t||"").trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9' -]/g,"").replace(/\s+/g," ").trim();}
function looksEnglish(t){const s=String(t||"").trim();return s&&hasLatin(s)&&!hasJapanese(s);}
function looksJapanese(t){const s=String(t||"").trim();return s&&hasJapanese(s);}

function validateVocabCandidate({rawQuestion,mode,expectedSource,recentSet,eligibleWeakSet,cooldownSet,selectedSet}){
  try{
    const q=rawQuestion||{};const prompt=String(q.prompt||"").trim(),context=String(q.context||"").trim(),word=String(q.word||"").trim(),meaning_ja=String(q.meaning_ja||"").trim(),explanation_ja=String(q.explanation_ja||"").trim();const options=Array.isArray(q.options)?q.options.map(x=>String(x||"").trim()):[];const key=normalizeWord(word),ai=answerIndex(q);
    if(!word||!key)throw new Error("word is empty");if(selectedSet.has(key))throw new Error(`duplicate in current set: ${word}`);if(options.length!==4||new Set(options.map(x=>x.toLowerCase())).size!==4)throw new Error("invalid options");if(ai===null)throw new Error("invalid answer_index");
    if(mode==="blank"){if((prompt.match(/_____/g)||[]).length!==1||!hasLatin(prompt)||hasJapanese(prompt))throw new Error("invalid blank prompt");if(!options.every(looksEnglish))throw new Error("blank options must be English");if(normalizeWord(options[ai])!==key)throw new Error("blank correct option mismatch");}
    if(mode==="en-ja"){if(!hasLatin(prompt)||hasJapanese(prompt)||normalizeWord(prompt)!==key)throw new Error("invalid en-ja prompt");if(!options.every(looksJapanese))throw new Error("en-ja options must be Japanese");}
    if(mode==="ja-en"){if(!hasJapanese(prompt))throw new Error("invalid ja-en prompt");if(!options.every(looksEnglish))throw new Error("ja-en options must be English");if(normalizeWord(options[ai])!==key)throw new Error("ja-en correct option mismatch");}
    if(expectedSource==="new"&&recentSet.has(key))throw new Error(`recent word: ${word}`);if(expectedSource==="review"&&(!eligibleWeakSet.has(key)||cooldownSet.has(key)))throw new Error(`review unavailable: ${word}`);
    return{ok:true,question:{prompt,context,options,answer_index:ai,word,meaning_ja,explanation_ja,source:expectedSource}};
  }catch(e){return{ok:false,reason:e.message};}
}

const LISTENING_RANDOM_CATEGORIES=[
  ["restaurant","restaurant, cafe, ordering food, or making a reservation"],["work","workplace, meeting, coworker, deadline, or office communication"],["shopping","shopping, returning an item, asking about a product, or paying"],["hotel","hotel, check-in, check-out, room request, or accommodation"],["school","school, class, studying, assignment, or campus life"],["health","health, pharmacy, clinic, appointment, or describing a minor symptom"],["home","home, household task, cooking, cleaning, or a small problem at home"],["friends","friends, making plans, changing plans, invitation, or social activity"],["phone","phone call, voicemail, message, or contacting someone"],["delivery","delivery, package, online order, receiving an item, or shipping"],["bank","banking, payment, ATM, bill, or simple financial service"],["event","event, concert, museum, movie, ticket, or public activity"],["travel","travel planning, sightseeing, airport, luggage, or tourist information"],["transport","public transportation, train, bus, taxi, station, or route"],["weather","weather, changing plans because of weather, or preparing for conditions"],["service","customer service, asking for help, making a request, or solving a service problem"],["appointment","appointment, schedule, rescheduling, or confirming a time"],["technology","computer, smartphone, internet, simple technical problem, or online service"],["neighborhood","neighborhood, local facility, asking for directions, or community activity"],["daily","ordinary daily life, errands, routine plans, or a small everyday decision"]
].map(([id,label])=>({id,label}));
let recentRandomCategories=[];
function chooseListeningCategory(){const blocked=new Set(recentRandomCategories.slice(-5));let c=LISTENING_RANDOM_CATEGORIES.filter(x=>!blocked.has(x.id));if(!c.length)c=LISTENING_RANDOM_CATEGORIES;const s=c[Math.floor(Math.random()*c.length)];recentRandomCategories=[...recentRandomCategories,s.id].slice(-20);return s;}

app.post("/api/listening",requireKey,async(req,res)=>{try{
  const mode=String(req.body.mode||"dictation"),level=String(req.body.level||"B1"),requestedTopic=String(req.body.topic||"Random"),length=String(req.body.length||"short");const recent=Array.isArray(req.body.recentListening)?req.body.recentListening.map(x=>String(x||"").trim()).filter(Boolean).slice(-20):[];const veryRecent=recent.slice(-5);let actualTopic=requestedTopic;let selected=null;if(requestedTopic.trim().toLowerCase()==="random"){selected=chooseListeningCategory();actualTopic=selected.label;}const lengthRule=length==="short"?"8-14 words":length==="medium"?"15-28 words":"29-50 words";const recentText=recent.length?recent.map((x,i)=>`${i+1}. ${x}`).join("\n"):"(none)";const recent5=veryRecent.length?veryRecent.map((x,i)=>`${i+1}. ${x}`).join("\n"):"(none)";
  const variety=`Actual scenario category: ${actualTopic}\nRecent exercises:\n${recentText}\nFive most recent:\n${recent5}\nRules: do not repeat the same underlying event, location+problem+goal+outcome, or communicative purpose. Missing a bus/train/subway all count as essentially the same scenario. Keep it natural and realistic. If Random, use the selected category but create a fresh situation.`;
  const prompt=mode==="mcq"?`Create ONE English listening comprehension exercise for a Japanese learner. CEFR ${level}. Length ${lengthRule}. ${variety}\nReturn ONLY JSON: {"sentence":"...","translation":"...","listening_tip":"...","scenario":"...","questions":[{"question":"...","options":["A","B","C","D"],"answer_index":0,"explanation_ja":"..."},{"question":"...","options":["A","B","C","D"],"answer_index":1,"explanation_ja":"..."},{"question":"...","options":["A","B","C","D"],"answer_index":2,"explanation_ja":"..."}]} Exactly 3 questions, 4 English options each, answers supported by audio, natural CEFR ${level}, no markdown.`:`Create ONE English listening dictation exercise for a Japanese learner. CEFR ${level}. Length ${lengthRule}. ${variety}\nReturn ONLY JSON: {"sentence":"...","translation":"...","listening_tip":"...","scenario":"..."}. Natural useful CEFR ${level}, no markdown.`;
  let data,last;for(let i=0;i<2;i++){try{data=await generateJson(prompt);if(!data?.sentence)throw new Error("Listening英文が生成されませんでした。");if(mode==="mcq")validateQuestions(data.questions,3);break;}catch(e){data=null;last=e;}}
  if(!data)throw last||new Error("Listening問題の生成に失敗しました。");res.json(data);
}catch(e){console.error(e);res.status(500).json({error:e.message||"問題作成に失敗しました。"});}});

app.post("/api/vocabulary",requireKey,async(req,res)=>{try{
  const level=String(req.body.level||"B1"),topic=String(req.body.topic||"Daily conversation"),mode=String(req.body.mode||"en-ja");if(!["en-ja","ja-en","blank"].includes(mode))throw new Error("Vocabularyの出題形式が不正です。");const count=Math.max(5,Math.min(15,Number(req.body.count)||10));const recentWords=Array.isArray(req.body.recentWords)?req.body.recentWords.map(x=>String(x||"").trim()).filter(Boolean).slice(-200):[];const weakWords=Array.isArray(req.body.weakWords)?req.body.weakWords.map(x=>({word:String(x?.word||"").trim(),meaning_ja:String(x?.meaning_ja||"").trim(),count:Number(x?.count||1)})).filter(x=>x.word).slice(0,40):[];
  const cooldownSet=new Set(recentWords.slice(-30).map(normalizeWord));const eligibleWeak=weakWords.filter(x=>!cooldownSet.has(normalizeWord(x.word))).sort((a,b)=>b.count-a.count);const eligibleWeakSet=new Set(eligibleWeak.map(x=>normalizeWord(x.word)));const recentSet=new Set(recentWords.map(normalizeWord));const desiredReview=Math.min(Math.round(count*.2),eligibleWeak.length);const selected=[],selectedSet=new Set();
  const modeRule=mode==="blank"?`MODE blank: prompt is one natural English sentence with exactly one _____; options are four English words/phrases; word is correct option; meaning_ja Japanese; context empty.`:mode==="ja-en"?`MODE ja-en: prompt is Japanese meaning only; options are four English words/phrases; correct option exactly equals word; meaning_ja Japanese.`:`MODE en-ja: prompt is one English word/phrase exactly equal to word; options are four Japanese meanings; meaning_ja Japanese.`;
  async function candidates(source,needed){const n=Math.min(15,Math.max(5,needed+3));const recentText=recentWords.join(", ")||"(none)";const weakText=eligibleWeak.map(x=>`${x.word} (${x.meaning_ja})`).join(", ")||"(none)";const selectedText=Array.from(selectedSet).join(", ")||"(none)";const src=source==="review"?`Choose targets ONLY from eligible weak words: ${weakText}. Do not use already selected: ${selectedText}.`:`Choose NEW useful CEFR ${level} vocabulary for topic ${topic}. Do not use recent words: ${recentText}. Do not use already selected: ${selectedText}. Avoid trivial inflection/singular/plural workarounds.`;const p=`Create ${n} candidate vocabulary questions. ${modeRule} ${src} Return ONLY JSON {"questions":[{"prompt":"...","context":"...","options":["...","...","...","..."],"answer_index":0,"word":"...","meaning_ja":"...","explanation_ja":"..."}]}. Exactly ${n} candidates, 4 options each, no markdown.`;const d=await generateJson(p);return Array.isArray(d.questions)?d.questions:[];}
  function accept(arr,source,max){let a=0;for(const raw of arr){if(a>=max)break;const r=validateVocabCandidate({rawQuestion:raw,mode,expectedSource:source,recentSet,eligibleWeakSet,cooldownSet,selectedSet});if(!r.ok){console.log(`Vocabulary candidate rejected (${source}):`,r.reason);continue;}selected.push(r.question);selectedSet.add(normalizeWord(r.question.word));a++;}return a;}
  let remReview=desiredReview;for(let i=0;i<3&&remReview>0;i++){try{remReview-=accept(await candidates("review",remReview),"review",remReview);}catch(e){console.warn(e.message);}}
  let remNew=count-selected.length;for(let i=0;i<5&&remNew>0;i++){try{remNew-=accept(await candidates("new",remNew),"new",remNew);}catch(e){console.warn(e.message);}}
  if(selected.length<count)throw new Error(`問題を十分に生成できませんでした。${selected.length}/${count}問まで作成できました。もう一度お試しください。`);const final=selected.slice(0,count);for(let i=final.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[final[i],final[j]]=[final[j],final[i]];}res.json({questions:final});
}catch(e){console.error(e);res.status(500).json({error:e.message||"単語問題の作成に失敗しました。"});}});

app.post("/api/vocabulary-check",requireKey,async(req,res)=>{try{
  const mode=String(req.body.mode||""),prompt=String(req.body.prompt||""),context=String(req.body.context||""),word=String(req.body.word||""),meaningJa=String(req.body.meaning_ja||""),userAnswer=String(req.body.userAnswer||"").trim();if(!["en-ja","ja-en","blank"].includes(mode))return res.status(400).json({error:"Vocabularyの出題形式が不正です。"});if(!userAnswer)return res.status(400).json({error:"回答が入力されていません。"});
  const rule=mode==="en-ja"?`Learner saw English and answered in Japanese. Accept natural Japanese synonyms/paraphrases with the same meaning.`:mode==="ja-en"?`Learner saw Japanese and answered in English. Accept genuinely equivalent English answers. Minor spelling errors may be accepted only if intention is unmistakable and no different word is created.`:`Learner filled an English sentence blank. Accept an alternative only if it fits this exact sentence naturally, grammatically and semantically.`;
  const p=`Grade one vocabulary answer. Mode: ${mode}. Prompt: ${prompt}. Context: ${context||"(none)"}. Target English: ${word}. Target Japanese meaning: ${meaningJa}. Learner answer: ${userAnswer}. ${rule} Be fair but not over-generous. Return ONLY JSON {"correct":true,"score":100,"feedback_ja":"short Japanese feedback","accepted_answer":"best standard answer"}. score integer 0-100; >=80 means correct, <80 incorrect; no markdown.`;
  const d=await generateJson(p);const score=Math.max(0,Math.min(100,Math.round(Number(d.score)||0)));res.json({correct:score>=80,score,feedback_ja:String(d.feedback_ja||""),accepted_answer:String(d.accepted_answer||(mode==="en-ja"?meaningJa:word))});
}catch(e){console.error(e);res.status(500).json({error:e.message||"回答判定に失敗しました。"});}});

app.post("/api/reading",requireKey,async(req,res)=>{try{const level=String(req.body.level||"B1"),topic=String(req.body.topic||"Daily conversation"),length=String(req.body.length||"medium"),count=Math.max(3,Math.min(5,Number(req.body.count)||4)),words=length==="short"?"90-130":length==="medium"?"160-230":"280-380";const p=`Create ONE English reading comprehension exercise for a Japanese learner. CEFR ${level}. Topic ${topic}. Passage about ${words} words. Return ONLY JSON {"passage":"...","translation":"...","questions":[{"question":"...","options":["A","B","C","D"],"answer_index":0,"explanation_ja":"..."}],"key_vocabulary":[{"word":"...","meaning_ja":"..."}]}. Exactly ${count} questions, 4 English options each, mix main idea/detail/vocabulary/inference, 4-8 key vocabulary, no markdown.`;const d=await generateJson(p);validateQuestions(d.questions,count);res.json(d);}catch(e){console.error(e);res.status(500).json({error:e.message||"リーディング問題の作成に失敗しました。"});}});

app.post("/api/speech",requireKey,async(req,res)=>{try{const text=String(req.body.text||"").trim();if(!text)return res.status(400).json({error:"読み上げる英文がありません。"});const r=await fetch("https://api.openai.com/v1/audio/speech",{method:"POST",headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-4o-mini-tts",voice:"alloy",input:text,response_format:"mp3"})});if(!r.ok)return res.status(r.status).json({error:(await r.text())||"音声生成に失敗しました。"});res.set("Content-Type","audio/mpeg");res.send(Buffer.from(await r.arrayBuffer()));}catch(e){console.error(e);res.status(500).json({error:e.message||"音声生成に失敗しました。"});}});

app.post("/api/explain",requireKey,async(req,res)=>{try{const sentence=String(req.body.sentence||""),answer=String(req.body.answer||"");const p=`You are an English listening coach for a Japanese learner. Correct English: ${sentence}. Learner's dictation: ${answer}. Return ONLY JSON {"feedback":"Japanese feedback in 3-5 concise sentences","focus":["short Japanese focus point 1","short Japanese focus point 2"]}. Explain what was correct/missed, likely listening causes such as linking/weak forms/reductions/rhythm, and one practice tip. No markdown.`;res.json(await generateJson(p));}catch(e){console.error(e);res.status(500).json({error:e.message||"解説生成に失敗しました。"});}});

app.listen(PORT,"0.0.0.0",()=>console.log(`English Trainer running on port ${PORT}`));
